apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-auth-image
  namespace: dev
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: IMAGE
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/shared-workspace
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ecr-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ecr-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-east-1
      args:
        - "--dockerfile=/workspace/Kubernetes_tekton_project/auth-service/Dockerfile"
        - "--context=/workspace/Kubernetes_tekton_project/auth-service"
        - "--destination=$(params.IMAGE)"
