apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: devsecops-pipeline
  namespace: dev
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: IMAGE

  tasks:
    - name: fetch
      taskRef:
        name: fetch-source
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace 
    - name: build
      taskRef:
        name: build-auth-image
      workspaces: 
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - fetch

    - name: test
      taskRef:
        name: unit-test
      runAfter:
        - build
